# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Pragmaticus"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Medium inspired, using only web-safe fonts"
homepage = "http://example.com/"
tags = ["readability", "fast", "minimal", "medium", "blog", "responsive", "seo"]
min_version = "0.41"

[author]
  name = "iPragmaticus"
  homepage = "http://ipragmaticus.com"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.br]
    languageName = "Português"
    weight = 2
